name: Run Tests + Allure Report

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Clean workspace
        run: |
          rm -rf allure-results
          rm -rf allure-report
          rm -rf target

      - name: Run tests
        run: mvn clean test

      - name: Debug workspace
        run: |
          echo "PWD: $(pwd)"
          ls -R .

      - name: Locate Allure results
        run: |
          echo "Searching allure-results..."
          find . -type d -name "allure-results"

      - name: Install Allure
        run: |
          ALLURE_VERSION=2.27.0
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
          tar -zxvf allure-${ALLURE_VERSION}.tgz

      - name: Generate Allure Report (SAFE)
        run: |
          RESULTS_DIR=$(pwd)/allure-results
          REPORT_DIR=$(pwd)/allure-report

          echo "Results dir: $RESULTS_DIR"
          echo "Report dir: $REPORT_DIR"

          ./allure-2.27.0/bin/allure generate "$RESULTS_DIR" --clean -o "$REPORT_DIR"

      - name: Verify report
        run: |
          ls -R allure-report
          test -f allure-report/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy Allure Report"